project_id = "victenancy-local"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]

[auth.email]
enable_signup = true
double_confirm_changes = false

[db]
port = 54322
major_version = 15

[api]
enabled = true
port = 54321

[studio]
enabled = true
port = 54323

[analytics]
enabled = false

[realtime]
enabled = true

[storage]
enabled = false

[inbucket]
enabled = false
